### PR TITLE
Question about reading in the country_names xls

### PR DESCRIPTION
**Pull request by Namkolla**
See comments on code.

### CODE REVIEW

**Review by rhtgpta — COMMENTED** [review]
Actually researchers don't need to provide anything, the csv file is the default file which has all the information that will ever be needed for countries and regions (unless some new countries are formed). 
I hope I am not missing something!

**Comment by Namkolla** [comment]
Great -- make sense!

Just to confirm, could region_inputs.xls for the portfolio_graphs script
work the same way? Assuming our RAs affiliate the same countries and
regions, they can use the spreadsheet you already built?

**Comment by rhtgpta** [comment]
If portfolio scraper can always be run first, we can get the countries/regions of interventions pre-populated.
However, it is not set up that way right now. 
Good suggestion, we should do it.

**Comment by rhtgpta** [comment]
Can you please open an issue for incorporating what we just discussed? Rough description works.
Will close this request now.

**Pull request closed without merging**
